<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ppdb;
use Carbon\Carbon;

class PpdbSeeder extends Seeder
{
    public function run()
    {
        $ppdbs = [
            [
                'id' => 1,
                'email' => 'nadia@gmail.com',
                'nama_lengkap' => 'nadia',
                'nik' => '5647547775',
                'no_kk' => '547345643',
                'nisn' => '43652',
                'ttl' => '456464756',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'ateis',
                'asal_sekolah' => '',
                'alamat' => 'shdsuwegdjjs',
                'nama_ayah' => 'andres',
                'nik_ayah' => '967050',
                'pekerjaan_ayah' => 'petani',
                'pendidikan_ayah' => 'hwefk',
                'no_telp_ayah' => '346326',
                'penghasilan_ayah' => '6576664',
                'nama_ibu' => 'virga',
                'nik_ibu' => '54',
                'pekerjaan_ibu' => 'petani',
                'pendidikan_ibu' => 'hwefk',
                'no_telp_ibu' => '346326',
                'penghasilan_ibu' => '6576664',
                'nama_wali' => null,
                'no_telp_wali' => null,
                'alamat_wali' => null,
                'foto_kk' => 'uploads/teByAtEfYi9pVm3uldcICNjU0mISUq9EKMQhNwyJ.jpg',
                'foto_ktp' => 'uploads/727rhdYi7PGl60oS3cfFuRxseU2R8pRoCilhskHb.jpg',
                'foto_akta' => 'uploads/CD3v0YcHaetIZbg8hwSCc5GQrnaqj5W5ygaow5P9.jpg',
                'foto_raport' => 'uploads/UWzFiyfOt2HoMhSWWobOeQlSCVM3cT2Nn1TOFkpf.jpg',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'verified',
                'created_at' => Carbon::parse('2025-03-05 22:23:41'),
                'updated_at' => Carbon::parse('2025-03-05 22:31:30'),
            ],
            [
                'id' => 3,
                'email' => 'riskyyunis@gmail.com',
                'nama_lengkap' => 'rizki yuniz ytta',
                'nik' => '774536',
                'no_kk' => '42564626',
                'nisn' => '642562542',
                'ttl' => 'blitar 12 januari 2001',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'islam',
                'asal_sekolah' => 'sdn bakung',
                'alamat' => 'blitar',
                'nama_ayah' => 'andres',
                'nik_ayah' => '967050',
                'pekerjaan_ayah' => 'petani',
                'pendidikan_ayah' => 'hwefk',
                'no_telp_ayah' => '346326',
                'penghasilan_ayah' => '6576664',
                'nama_ibu' => 'virga',
                'nik_ibu' => '54',
                'pekerjaan_ibu' => 'petani',
                'pendidikan_ibu' => 'hwefk',
                'no_telp_ibu' => '346326',
                'penghasilan_ibu' => '6576664',
                'nama_wali' => null,
                'no_telp_wali' => null,
                'alamat_wali' => null,
                'foto_kk' => 'uploads/lZs3mhlcIDbgMRi9GqzVkyh8dbsSLeydMSt8NIui.jpg',
                'foto_ktp' => 'uploads/qgiWpPxG8KwPVrJin0sVUUg9pXmErL0TMbC4ioqE.jpg',
                'foto_akta' => 'uploads/bS3mqbPWUqleuf4DBtJOOrlzcT8qrNMQU89Y4mA5.jpg',
                'foto_raport' => 'uploads/0PG1N9omU6sywAt4N1DZ50iA48INLDv9L05GWiy1.jpg',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'verified',
                'created_at' => Carbon::parse('2025-03-07 20:38:34'),
                'updated_at' => Carbon::parse('2025-04-09 21:02:52'),
            ],
            [
                'id' => 5,
                'email' => 'jonathan@gmail.com',
                'nama_lengkap' => 'jonathan',
                'nik' => '6589670832',
                'no_kk' => '345435646',
                'nisn' => '64444456',
                'ttl' => 'blitar 10 januari 2000',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'sadbjkwb',
                'asal_sekolah' => 'sdn blitar',
                'alamat' => 'blitar',
                'nama_ayah' => 'ilham',
                'nik_ayah' => '54747537',
                'pekerjaan_ayah' => 'hacker',
                'pendidikan_ayah' => 'smp',
                'no_telp_ayah' => '547845946',
                'penghasilan_ayah' => '3569535665',
                'nama_ibu' => 'virga',
                'nik_ibu' => '54',
                'pekerjaan_ibu' => 'cc',
                'pendidikan_ibu' => 'hwefk',
                'no_telp_ibu' => '4575858',
                'penghasilan_ibu' => '43654876869',
                'nama_wali' => null,
                'no_telp_wali' => null,
                'alamat_wali' => null,
                'foto_kk' => 'uploads/ZTFMMBz8E8lc4qJjBhKzXbr8DR0FBaravB3Zi7BO.png',
                'foto_ktp' => 'uploads/MWD3C6jYPo2nZLTMexy4vyXWXSRCOHslTJwLhFik.jpg',
                'foto_akta' => 'uploads/IQUc3oAZUYkBNTmJTAgTfr8rKBthGPfasfykTgTM.jpg',
                'foto_raport' => 'uploads/p3fZvTciZeoQR75kSWo1pET73K2XZE9Z9FK9NkQO.jpg',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'pending',
                'created_at' => Carbon::parse('2025-03-10 22:13:32'),
                'updated_at' => Carbon::parse('2025-03-10 22:13:32'),
            ],
            [
                'id' => 7,
                'email' => 'dani@gmail.com',
                'nama_lengkap' => 'Dani Budi Santoso',
                'nik' => '3578011708100001',
                'no_kk' => '35780117082011293',
                'nisn' => '0012345678',
                'ttl' => 'Surabaya, 20 Agustus 2010',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'islam',
                'asal_sekolah' => 'Sdn Sidomulyo 03',
                'alamat' => 'Dsn.kalimeneng RT 04 RW 03, Ds.Sidomulyo, Kec.Bakung, Kab.Blitar',
                'nama_ayah' => 'Bambang Santoso',
                'nik_ayah' => '3171020506780002',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMK',
                'no_telp_ayah' => '081122334455',
                'penghasilan_ayah' => '3000000',
                'nama_ibu' => 'Siti Aminah',
                'nik_ibu' => '3273031011800003',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'pendidikan_ibu' => 'SMA',
                'no_telp_ibu' => '085678901234',
                'penghasilan_ibu' => '1000000',
                'nama_wali' => 'nurin indah',
                'no_telp_wali' => '089763555144',
                'alamat_wali' => 'Dsn.kalimeneng RT 01 RW 03, Ds.Sidomulyo, Kec.Bakung, Kab.Blitar',
                'foto_kk' => 'uploads/0G6SH2D7ZhUp74pVu4tCA0StEBB2HqfFI0AubTv8.jpg',
                'foto_ktp' => 'uploads/uBfuC5BUAiDczm1mPdpE6UxeR8EB7GIO2hmemIPq.jpg',
                'foto_akta' => 'uploads/XnuDpu4WgpuK284dg1ZeKQ1XnfYzBJqyM9f5c9pn.jpg',
                'foto_raport' => 'uploads/4LJx33cDbBVCsGKmNdU5EFwKUDNE6pP1kntAQvRP.jpg',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'pending',
                'created_at' => Carbon::parse('2025-04-26 05:33:01'),
                'updated_at' => Carbon::parse('2025-04-26 05:33:01'),
            ],
            [
                'id' => 8,
                'email' => 'rahma@gmail.com',
                'nama_lengkap' => 'rahma andriana',
                'nik' => '357801170811111',
                'no_kk' => '35780117082010197',
                'nisn' => '0012345101',
                'ttl' => 'Blitar, 11 Januari 2011',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'islam',
                'asal_sekolah' => 'Sdn Sidomulyo 02',
                'alamat' => 'Dsn.kalibawang RT 02 RW 02, Ds.Sidomulyo, Kec.Bakung, Kab.Blitar',
                'nama_ayah' => 'hermawan',
                'nik_ayah' => '3171020506780001',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMA',
                'no_telp_ayah' => '098765111096',
                'penghasilan_ayah' => '3000000',
                'nama_ibu' => 'ana fitria',
                'nik_ibu' => '3273031011800002',
                'pekerjaan_ibu' => 'Wiraswasta',
                'pendidikan_ibu' => 'SMA',
                'no_telp_ibu' => '085678111222',
                'penghasilan_ibu' => '1000000',
                'nama_wali' => 'novia',
                'no_telp_wali' => '085444098765',
                'alamat_wali' => 'blitar',
                'foto_kk' => 'uploads/SV4CnE3qhoTaLAqjxgW1sKX3P6jhtEsfM0nFst09.jpg',
                'foto_ktp' => 'uploads/lTbYiKJJGyok8crznPAqcxb718vKwlAMoOBK8sbP.jpg',
                'foto_akta' => 'uploads/Lxol1uXPcfoJCmLIkLP1OPYaHJtZE6UOLvY5YjjM.jpg',
                'foto_raport' => 'uploads/eN7yx9WCL7yteNOt8X4TnMbE1L4CmbIkp3960ptK.jpg',
                'foto_ijazah' => 'uploads/0QAnjQcL1hilSrYaXoL2MUSOof8aEEKhxjc0VMvf.jpg',
                'foto_sertifikat' => null,
                'status_verifikasi' => 'pending',
                'created_at' => Carbon::parse('2025-04-26 21:18:09'),
                'updated_at' => Carbon::parse('2025-04-26 21:18:09'),
            ],
            [
                'id' => 9,
                'email' => 'rahma@gmail.com',
                'nama_lengkap' => 'rahma andriana',
                'nik' => '357801170811111',
                'no_kk' => '35780117082010197',
                'nisn' => '0012345101',
                'ttl' => 'Blitar, 11 Januari 2011',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'islam',
                'asal_sekolah' => 'Sdn Sidomulyo 02',
                'alamat' => 'blitar',
                'nama_ayah' => 'Bambang Santoso',
                'nik_ayah' => '3171020506780002',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMK',
                'no_telp_ayah' => '081122334455',
                'penghasilan_ayah' => '3000000',
                'nama_ibu' => 'ana fitria',
                'nik_ibu' => '3273031011800002',
                'pekerjaan_ibu' => 'Wiraswasta',
                'pendidikan_ibu' => 'SMA',
                'no_telp_ibu' => '098765111096',
                'penghasilan_ibu' => '1000000',
                'nama_wali' => null,
                'no_telp_wali' => null,
                'alamat_wali' => null,
                'foto_kk' => 'uploads/oNrfAIAyefo7Fr3lbzBmv6KuKgjfQRvXbmvhZD7k.jpg',
                'foto_ktp' => 'uploads/q6yvvCS2MiPNKTP0IhpR0uQmVd7cWkq733tOX7Cz.jpg',
                'foto_akta' => 'uploads/M8d8zRp79WxpRnhboFiCdXnqKJC9k7S6pn4MPpcw.jpg',
                'foto_raport' => 'uploads/FBOh6fU4lVvEKieAIVGel9RsFbYENqnDd9JpjotP.png',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'pending',
                'created_at' => Carbon::parse('2025-04-29 15:27:44'),
                'updated_at' => Carbon::parse('2025-04-29 15:27:44'),
            ],
            [
                'id' => 10,
                'email' => 'rima@gmail.com',
                'nama_lengkap' => 'rahma andriana',
                'nik' => '357801170811111',
                'no_kk' => '35780117082010197',
                'nisn' => '0012345101',
                'ttl' => 'Blitar, 11 Januari 2011',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'islam',
                'asal_sekolah' => 'Sdn Sidomulyo 02',
                'alamat' => 'blitar',
                'nama_ayah' => 'Bambang Santoso',
                'nik_ayah' => '3171020506780002',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMA',
                'no_telp_ayah' => '098765111096',
                'penghasilan_ayah' => '1000000',
                'nama_ibu' => 'ana fitria',
                'nik_ibu' => '3273031011800002',
                'pekerjaan_ibu' => 'Wiraswasta',
                'pendidikan_ibu' => 'SMA',
                'no_telp_ibu' => '098765111096',
                'penghasilan_ibu' => '1000000',
                'nama_wali' => null,
                'no_telp_wali' => null,
                'alamat_wali' => null,
                'foto_kk' => 'uploads/0HjIJYp5ffD35qQqqjtyGnLqTaD3VsCFKG0CmFXk.jpg',
                'foto_ktp' => 'uploads/9TiRXz1FfpwNvnNTJssudnWYfPz6HeMgFhFT0s6n.jpg',
                'foto_akta' => 'uploads/ukWpbosxTULVPJshupFJQTXEzJMEZ4Vrzd5Als41.png',
                'foto_raport' => 'uploads/Mk5FqdnbiZsr3QRyxxKxlLafu77EKO6zRxIz2WHK.jpg',
                'foto_ijazah' => null,
                'foto_sertifikat' => null,
                'status_verifikasi' => 'pending',
                'created_at' => Carbon::parse('2025-04-29 16:02:17'),
                'updated_at' => Carbon::parse('2025-04-29 16:02:17'),
            ],
        ];

        foreach ($ppdbs as $ppdb) {
            Ppdb::create($ppdb);
        }
    }
}